org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configureondemand=true
loom.ignoreDependencyLoomVersionValidation=true

# Project properties
archives_base_name=matthiesen-lib

mod_id=matthiesen_lib
mod_name=Matthiesen Lib
mod_description=A lightweight Architectury-style library for shared mod code across Fabric and NeoForge

api_mod_id=matthiesen_lib_api
api_mod_name=Matthiesen Lib API
api_mod_description=Server-side API for Matthiesen Lib, providing utilities and features for mod developers using the library

mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/matthiesen-lib/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/matthiesen-lib
git_url=github.com/Matthiesen-dev/matthiesen-lib.git

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1

# Testing dependencies
junit_version=5.1.0