org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=matthiesen-lib
mod_id=matthiesen_lib
mod_version=1.0.0-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Matthiesen Lib
mod_description=A library for my Mods
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/matthiesen-lib/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/matthiesen-lib
git_url=github.com/Matthiesen-dev/matthiesen-lib.git

#fabric project dependencies
fabric_loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1

#neoforge project dependencies
neoforge_version=21.1.182

#common dependencies
minecraft_version=1.21.1
junit_version=5.1.0