[versions]
# Kotlin
kotlin = "2.2.20"

# Plugins
idea-ext = "1.1.7"
publish = "0.35.0"
shadow = "9.4.1"

# Minecraft Development
minecraft = "1.21.1"
loom = "1.13-SNAPSHOT"
architectury-plugin = "3.4-SNAPSHOT"
neoforge = "21.1.182"
fabric_loader_version = "0.17.2"
fabric_api_version = "0.116.6+1.21.1"
fabric_permissions_api_version = "0.3.1"
sponge_mixin_version = "0.8.5"
emberstextapi_version = "2.9.4"
faststats_version = "0.25.2"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "loom" }
architectury-plugin = { id = "architectury-plugin", version.ref = "architectury-plugin" }

[libraries]
# General Buildscript Plugins
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
loom = { group = "dev.architectury", name = "architectury-loom", version.ref = "loom" }
ideaExt = { group = "org.jetbrains.gradle.plugin.idea-ext", name = "org.jetbrains.gradle.plugin.idea-ext.gradle.plugin", version.ref = "idea-ext"}
architectury = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "publish" }
shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }

# Development Libraries
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
minecraftNet = { group = "net.minecraft", name = "minecraft", version.ref = "minecraft" }
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader_version" }
fabricApi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api_version" }
fabricPermissionsApi = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabric_permissions_api_version" }
spongeMixin = { group = "org.spongepowered", name = "mixin", version.ref = "sponge_mixin_version" }
faststatsConfig = { group = "dev.faststats.metrics", name = "config", version.ref = "faststats_version" }
faststatsCore = { group = "dev.faststats.metrics", name = "core", version.ref = "faststats_version" }

emberstextapiFabric = { group = "net.tysontheember.emberstextapi", name = "emberstextapi-fabric-1.21.1", version.ref = "emberstextapi_version" }
emberstextapiNeoForge = { group = "net.tysontheember.emberstextapi", name = "emberstextapi-neoforge-1.21.1", version.ref = "emberstextapi_version" }

[bundles]
fabricModImplementation = ["fabric", "fabricApi"]
fabricModCompileOnly = ["fabricPermissionsApi"]
faststats = ["faststatsConfig", "faststatsCore"]