package dev.matthiesen.common.matthiesen_lib_api.core.interfaces;

/**
 * Interface to be implemented by mod containers of mods using MatthiesenLib. Provides necessary information for metrics and other features.
 */
public interface MatthiesenLibModContainer {
    /**
     * Gets the name of the mod. This is used for metrics and other features that require identification of the mod. The name should be unique to avoid conflicts with other mods using MatthiesenLib.
     * @return the name of the mod. This should be a human-readable name that identifies the mod, such as "My Cool Mod". It is recommended to use a unique name to avoid conflicts with other mods using MatthiesenLib, especially if multiple mods are developed by the same author or have similar names. The mod name is used in metrics to identify which mod is sending the data, and it can also be used in other features that require mod identification.
     */
    String getModName();

    /**
     * Gets the version of the mod. This is used for metrics and other features that require version information. The version should follow a standard format (e.g., "1.0.0") to allow for proper parsing and analysis.
     * @return the version of the mod. This should be a string that follows a standard versioning format, such as "1.0.0" or "2.5.1". Providing a version allows for better analysis of metrics data, as it enables tracking of which versions of the mod are being used and how they perform. It also helps in identifying potential issues or trends related to specific versions of the mod. The version information can be crucial for debugging and improving the mod over time, as it provides context for the metrics collected and can help identify when certain features were introduced or when bugs were fixed.
     */
    String getModVersion();

    /**
     * Gets the platform of the mod. This is used for metrics and other features that require platform information. The platform should be a string that identifies the mod loader or environment the mod is running on (e.g., "fabric", "neoforge").
     * @return the platform of the mod. This should be a string that identifies the mod loader or environment the mod is running on, such as "fabric" or "neoforge". Providing platform information allows for better analysis of metrics data, as it enables tracking of which platforms are being used and how they perform. It also helps in identifying potential issues or trends related to specific platforms, as different mod loaders may have different performance characteristics or compatibility issues. The platform information can be crucial for debugging and improving the mod over time, as it provides context for the metrics collected and can help identify when certain features were introduced or when bugs were fixed in relation to specific platforms.
     */
    String getPlatform();

    /**
     * Gets the metric ID for the mod, which is a combination of the platform and a normalized version of the mod name. This is used for metrics to uniquely identify the mod in a consistent format. The metric ID is generated by concatenating the platform with a normalized version of the mod name, where spaces are replaced with underscores and all characters are converted to lowercase.
     * @return the metric ID for the mod, which is a combination of the platform and a normalized version of the mod name. The format of the metric ID is "{platform}:{normalized_mod_name}", where "normalized_mod_name" is derived from the mod name by converting it to lowercase and replacing all whitespace characters with underscores. For example, if the mod name is "My Cool Mod" and the platform is "fabric", the resulting metric ID would be "fabric:my_cool_mod". This standardized format allows for consistent identification of mods in metrics data, making it easier to analyze and compare metrics across different mods and platforms.
     */
    default String getModMetricId() {
        return getPlatform() + ":" + getModName().toLowerCase().replaceAll("\\s+", "_");
    }

    /**
     * Enum representing supported platforms for mods using MatthiesenLib. This enum provides a standardized way to identify the mod loader or environment the mod is running on, which can be used in metrics and other features that require platform information. Each enum constant has a label that can be used for display purposes or in metrics data.
     */
    enum Platform {
        /**
         * Represents the Fabric mod loader platform. This is one of the supported platforms for mods using MatthiesenLib, and it is identified by the label "fabric". Mods running on this platform can use this enum constant to indicate their platform in metrics and other features that require platform information.
         */
        FABRIC("fabric"),

        /**
         * Represents the NeoForge mod loader platform. This is one of the supported platforms for mods using MatthiesenLib, and it is identified by the label "neoforge". Mods running on this platform can use this enum constant to indicate their platform in metrics and other features that require platform information.
         */
        NEOFORGE("neoforge");

        private final String label;

        /**
         * Constructs a new Platform enum constant with the given label. The label is used to identify the platform in metrics and other features that require platform information. Each enum constant has a unique label that corresponds to the mod loader or environment it represents.
         * @param label the label for the platform, used to identify it in metrics and other features. This should be a string that corresponds to the mod loader or environment the platform represents, such as "fabric" for the Fabric mod loader or "neoforge" for the NeoForge mod loader. The label is stored in a private final field and can be retrieved using the getLabel method, allowing for consistent identification of platforms across different mods and features that require this information.
         */
        Platform(String label) {
            this.label = label;
        }

        /**
         * Gets the label for the platform, which is used to identify it in metrics and other features that require platform information. The label corresponds to the mod loader or environment the platform represents, such as "fabric" for the Fabric mod loader or "neoforge" for the NeoForge mod loader. This method allows for retrieval of the platform label, which can be used in metrics data and other features that require consistent identification of platforms.
         * @return the label for the platform, used to identify it in metrics and other features. This should be a string that corresponds to the mod loader or environment the platform represents, such as "fabric" for the Fabric mod loader or "neoforge" for the NeoForge mod loader. The label is stored in a private final field and can be retrieved using this method, allowing for consistent identification of platforms across different mods and features that require this information.
         */
        public String getLabel() {
            return label;
        }
    }
}
